# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reprint.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 700)

        # ===== STYLE =====
        Dialog.setStyleSheet("""
        QDialog {
            background-color: #f5f7fa;
        }

        QLabel#title {
            font-size: 32px;
            font-weight: bold;
            color: #2c3e50;
        }

        QLabel#subtitle {
            font-size: 22px;
            color: #606266;
        }

        QLineEdit {
            border: 2px solid #dcdfe6;
            border-radius: 10px;
            padding: 12px;
            font-size: 24px;
            background: white;
        }

        QLineEdit:focus {
            border-color: #409eff;
        }

        QGroupBox {
            border: none;
            border-radius: 15px;
            background: white;
            margin-top: 20px;
            font-size: 20px;
            font-weight: bold;
        }

        QGroupBox::title {
            subcontrol-origin: margin;
            left: 20px;
            padding: 5px 10px;
            color: #606266;
        }

        QLabel.value {
            background: #f0f2f5;
            border-radius: 8px;
            padding: 10px;
            font-size: 22px;
        }

        QLabel.label {
            font-size: 20px;
            color: #909399;
        }

        QLabel#status {
            border-radius: 10px;
            padding: 15px;
            font-size: 24px;
            background: #ecf5ff;
            color: #409eff;
        }
        """)

        # ===== MAIN LAYOUT =====
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(40, 40, 40, 40)
        self.verticalLayout.setSpacing(20)

        # ===== TITLE =====
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("title")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label)

        # ===== INPUT =====
        self.Input = QtWidgets.QLineEdit(Dialog)
        self.Input.setMinimumHeight(60)
        self.verticalLayout.addWidget(self.Input)

        # ===== SUBTITLE =====
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("subtitle")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label_7)

        # ===== GROUP BOX =====
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.verticalLayout.addWidget(self.groupBox)

        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setSpacing(15)

        # Labels
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setProperty("class", "label")

        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setProperty("class", "label")

        self.part_3 = QtWidgets.QLabel(self.groupBox)
        self.part_3.setProperty("class", "label")

        # Values
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setProperty("class", "value")

        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setProperty("class", "value")

        self.p_part_3 = QtWidgets.QLabel(self.groupBox)
        self.p_part_3.setProperty("class", "value")

        # Add to layout
        self.gridLayout.addWidget(self.label_2, 0, 0)
        self.gridLayout.addWidget(self.label_3, 0, 1)

        self.gridLayout.addWidget(self.label_4, 1, 0)
        self.gridLayout.addWidget(self.label_5, 1, 1)

        self.gridLayout.addWidget(self.part_3, 2, 0)
        self.gridLayout.addWidget(self.p_part_3, 2, 1)

        # ===== STATUS =====
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("status")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.verticalLayout.addWidget(self.label_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle("App")
        self.label.setText("PIEZO PCB PAIRING")
        self.label_7.setText("SCAN SERIAL NUMBER")
        self.groupBox.setTitle("Information")

        self.label_2.setText("WIP")
        self.label_4.setText("PCB")
        self.part_3.setText("Piezo")

        self.label_3.setText("")
        self.label_5.setText("")
        self.p_part_3.setText("")

        self.label_6.setText("Waiting for scan...")
